[project]
name = "ortho-para-h2-kinetics"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
equilibrium = "PYTHONPATH=./src python -c \"import os; os.makedirs('figs', exist_ok=True); from ortho_para.plots import plot_equilibrium_curve; plot_equilibrium_curve(show=True, save='figs/equilibrium.png')\""
relaxation  = "PYTHONPATH=./src python -c \"import os; os.makedirs('figs', exist_ok=True); from ortho_para.plots import plot_relaxation; plot_relaxation(T=20.0, show=True, save='figs/relaxation_T20K.png')\""
test        = "PYTHONPATH=./src pytest -q"

[dependencies]
python = ">=3.10"
numpy = "*"
scipy = "*"
matplotlib = "*"
pytest = "*"
