[project]
name = "ortho-para-h2-kinetics"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
# Explicitly call scripts via Python
equilibrium = "python ./scripts/plot_equilibrium.py"
relaxation = "python ./scripts/plot_relaxation.py"
test = "pytest -q"

[dependencies]
python = ">=3.10"
numpy = "*"
scipy = "*"
matplotlib = "*"
pytest = "*"
