[project.scripts]
equilibrium = "ortho_para.plots:plot_equilibrium_curve"
relaxation = "ortho_para.plots:plot_relaxation"

ortho-feq = "ortho_para.plots:cli_equilibrium"
ortho-relax = "ortho_para.plots:cli_relaxation"
ortho-fitk = "ortho_para.plots:cli_fit_k"
